// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWwnB63gybtEx73j6IGUf3G7eXgNKvWPk',
    appId: '1:78903841535:web:52e64e2c12e4c391a0b2ca',
    messagingSenderId: '78903841535',
    projectId: 'langverse-acbef',
    authDomain: 'langverse-acbef.firebaseapp.com',
    storageBucket: 'langverse-acbef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJC3guZQH66RigsohnyhYoN6GY4B9DNso',
    appId: '1:78903841535:android:da9b6ba9d23d655ca0b2ca',
    messagingSenderId: '78903841535',
    projectId: 'langverse-acbef',
    storageBucket: 'langverse-acbef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-1nK9f7VtaP-Fi6pEg_U8jPlp9W8YsXo',
    appId: '1:78903841535:ios:122d5709f6a31fb4a0b2ca',
    messagingSenderId: '78903841535',
    projectId: 'langverse-acbef',
    storageBucket: 'langverse-acbef.appspot.com',
    iosBundleId: 'com.example.langverse',
  );
}
